name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mbspcruz
          svg_out_path: dist/github-contribution-grid-snake.svg

        # Set PR_NUMBER environment variable
        env:
          PR_NUMBER: ${{ github.event.number }}

      # Assign PR to user
      - name: Assign user
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -d '{"assignees": ["mbspcruz"]}' \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/assignees

      # Publish to GitHub Pages
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
